### ISSUE TITLE
using bindgen, reproducing build

### ISSUE THREAD

**Issue by greluc** [samcrow/xplm-sys#4]
Hi,

I'm trying to generate the bindings myself. But I always run into problems when using bindgen. No matter if I use the CLI or the build.rs variant of bindgen. I always get the error that the header files are not found (`Unable to generate bindings: ClangDiagnostic("src/combined.h:5:10: fatal error: 'XPStandardWidgets.h' file not found\n")`).
Could you please share the steps on how to use bindgen with this setup?

I'm still a beginner with Rust and C, but would love to help with xplm-sys and rust-xplm and learn something in the process. :-)

**Comment by samcrow** [comment]
XPStandardWidgets.h is part of the plugin SDK distribution, which is in the SDK folder of this repository. The bindgen command in [generate.sh](https://github.com/samcrow/xplm-sys/blob/master/generate.sh) should include the correct options so bindgen can find all the header files. Is that the command you tried?
