### ISSUE TITLE
Upgrade SDK to 4.0

### ISSUE THREAD

**Issue by KnedlikMCPE** [samcrow/xplm-sys#5]
It would be helpful to upgrade the SDK, as 4.0 adds AArch64 (Apple Silicon) support for MacOS clients.

**Comment by samcrow** [comment]
It looks like this fork has that change: https://github.com/greluc/xplm-sys
If anyone makes a pull request here, I'll accept it.

**Comment by samcrow** [comment]
I merged https://github.com/samcrow/xplm-sys/pull/6 , but when publishing discovered a new problem:
The build script needs to put the generated file in OUT_DIR, not in src. The lib.rs file can then use `include!` to access that file.

**Comment by samcrow** [comment]
I just published v0.5.0 with the changes.
